import {
  Baby,
  Bath,
  BellRing,
  Building2,
  Car,
  Castle,
  Coffee,
  Dumbbell,
  Flame,
  FlameKindling,
  House,
  Laptop,
  type LucideIcon,
  LucideProps,
  Mountain,
  MountainSnow,
  PawPrint,
  PenTool,
  PlugZap,
  Sailboat,
  Shirt,
  Snowflake,
  Sparkles,
  Sun,
  TentTree,
  Thermometer,
  TreePalm,
  Trees,
  Tv,
  Umbrella,
  Utensils,
  WashingMachine,
  Waves,
  Wheat,
  Wifi,
  Wind,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  baby: Baby,
  bath: Bath,
  "bell-ring": BellRing,
  "building-2": Building2,
  car: Car,
  castle: Castle,
  coffee: Coffee,
  dumbbell: Dumbbell,
  flame: Flame,
  "flame-kindling": FlameKindling,
  house: House,
  laptop: Laptop,
  mountain: Mountain,
  "mountain-snow": MountainSnow,
  "paw-print": PawPrint,
  "pen-tool": PenTool,
  "plug-zap": PlugZap,
  sailboat: Sailboat,
  shirt: Shirt,
  snowflake: Snowflake,
  sparkles: Sparkles,
  sun: Sun,
  "tent-tree": TentTree,
  thermometer: Thermometer,
  palmtree: TreePalm,
  trees: Trees,
  tv: Tv,
  umbrella: Umbrella,
  utensils: Utensils,
  "washing-machine": WashingMachine,
  waves: Waves,
  wheat: Wheat,
  wifi: Wifi,
  wind: Wind,
};

export function Icon({ name, ...props }: { name: string } & LucideProps) {
  const Cmp = ICONS[name] ?? Sparkles;
  return <Cmp {...props} />;
}
